### PR TITLE
Fix hubot not reconnecting after st2ctl restart

### PR DESCRIPTION
**Pull request by enykeev**
When st2api is down, instead of 502 nginx will start returning special pages for custom resources and 404 for everything else.

In case of steam custom resource page, by changing `retry` value you can actually tell hubot how long it should wait before reconnecting.

### CODE REVIEW

**Comment by emedvedev** [comment]
404 doesn't seem accurate since API being down is not just "not found" but a genuine server error. How about HTTP 500?

**Comment by enykeev** [comment]
It's 404 now because we don't have custom answer in `@errors` location for anything except of /steam. The fix is outside the scope of that PR.

**Comment by emedvedev** [comment]
Would it be difficult to have a `return 500;` for every page except `stream` inside `@errors`? It's outside the scope, but I feel like having 404s on server errors is a bit of a regression, so it's not too hard, I'd rather fix it now.

**Comment by enykeev** [comment]
Honestly, I don't know how hard it would be, "I'm not a real welder", so to say.

**Pull request merged**
