### PR TITLE
Show friendly message when user hits /tokens endpoint

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by enykeev** [comment]
@jfryman please explain to me one more time why this doesn't update `/etc/nginx/sites-avaliable/st2webui.conf` on `sudo update-system`. I clearly missing something again.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1449764940011733

**Comment by jfryman** [comment]
I'll add some better docs on this, but try adding `ENV=current_working_directory` when you call `update-system` if you're trying to apply on a test machine locally.

**Comment by enykeev** [comment]
Yeah, I will now. I don't know why it working without it in some cases, but I'm done experimenting.

**Pull request merged**
