### PR TITLE
[WIP] Adding puppet-st2 branch

### PR DESCRIPTION
**Pull request by jfryman**
:warning: THIS IS WIP Putting up here for visibily and early comments :warning:

This PR takes a pass at adding the ability to deploy any arbitrary branch of `puppet-st2` and `st2workroom` at the same time.

This also takes a pass at solving the "I don't know Bash" problem. Adding OS support should be straightforward, and expanding the pre-boot and bootstrap scripts should be the same. This moves the pattern to small, well defined and named functions that should easily be understood by anyone who can understand formal logic. Bash ugliness is hidden as much as possible in scoped functions.

This is mostly done, running it through testing and working out small bugs.

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450739722017199

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450765508017344

**Comment by jfryman** [comment]
Because :rage:

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1452279896021798

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1452279966021801

**Pull request closed without merging**
