### PR TITLE
Removing default pack install

### PR DESCRIPTION
**Pull request by DoriftoShoes**
Per customer feedback I am removing the default installation of packs.

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1449795619012072

**Comment by jfryman** [comment]
:+1:

**Comment by manasdk** [comment]
How is estee-tew responding here? what is this magic!

**Comment by manasdk** [comment]
:100:

**Comment by Kami** [comment]
Bye bye :waving:

**Comment by jfryman** [comment]
@manasdk https://github.com/StackStorm/st2-stackstorm/pull/5

**Comment by enykeev** [comment]
Just make sure st2 pack stays here or it will break chatops in most horrible ways. Still think we should just make it core one too.

**Comment by jfryman** [comment]
👍 to st2 being core.

**Comment by DoriftoShoes** [comment]
st2 pack is in common.yaml.  I'm gonna merge this.

**Pull request merged**
