### PR TITLE
Accept Answers File

### PR DESCRIPTION
**Pull request by jfryman**
This PR adds the ability for the installer to accept an answers file at startup.

### CODE REVIEW

**Comment by DoriftoShoes** [comment]
+1.  Now we just need to give support to passing it the answers file via user-data.

**Comment by jfryman** [comment]
@DoriftoShoes Good point. Hmmmm. I'll file a bug, but let's deal with that later.

**Comment by dzimine** [comment]
Cool. So the format is hiera, we'll provide a sample :cool:

**Comment by jfryman** [comment]
quzztzn

**Pull request merged**
