### PR TITLE
Pin pip version to < 8.0.0

### PR DESCRIPTION
**Pull request by m4dcoder**
The latest pip version causes some dependencies not to be upgraded.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
There is at least one other place which is not fixed in this PR 
https://github.com/StackStorm/st2workroom/blob/master/modules/profile/manifests/python.pp#L15

**Comment by Kami** [comment]
Is it confirmed that this fixes the installation issue or not?

**Comment by Kami** [comment]
I checked the whole module, I believe this is not executing because we use `refreshonly => true`.

I will look into it.

**Comment by Kami** [comment]
Alright, I confirmed this branch now fixes the problem (`ENV=current_working_directory DEBUG=1 bash install.sh -r fix-pip`).

I will go ahead and merge it into master.

**Comment by jfryman** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1453336648028711 👍

**Pull request merged**
