### PR TITLE
Self-check Polish

### PR DESCRIPTION
**Pull request by jfryman**
This PR updates the self-check script to ask for user credentials if they are not set, allowing the self check to actually work properly.

### CODE REVIEW

**Comment by Kami** [comment]
LGTM :+1:

**Comment by jfryman** [comment]
@doriftoshoes can I also trouble you s/key/token/ in the prompt language. Want to keep our works consistent.

**Comment by jfryman** [comment]
Ok. My concern about this breaking CI is unfounded. We already skip the self-check there, so this cosmetic won't cause any :heart: :fire:

**Comment by DoriftoShoes** [comment]
Yeah I think we want to say token.

**Pull request merged**
