### PR TITLE
Make mongodb container to listen on localhost only

### PR DESCRIPTION
**Pull request by fatganz**

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

The change looks reasonable to me, but I'm not fully sure how this will affect the whole installation. We need to make sure other services can still talk to MongoDB.

In any case, I will wait for someone with more experience with this to chime in :)

**Comment by fatganz** [comment]
Just keep in mind that mongo container is exposed to the internet on freshly provisioned machines without authentication. So it would be really nice to fix this issue.

**Comment by jfryman** [comment]
@fatganz nice, thanks for the change. Any issues on your end after this change?

It shouldn't affect anything, since everything connects on localhost by default, but would love to just get a quick gut-check before merging.

**Comment by fatganz** [comment]
@jfryman So far there're no issues for me

**Comment by jfryman** [comment]
@fatganz :metal: We'll keep an eye on things and run through tests. Thanks again for the code and safety! :heart: :lock:

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450887659018288

**Pull request merged**
